name: "Github environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ vars.GITHUB_EVENT_NAME }}
        shell: cmd
      - run: echo ${{ vars.GITHUB_REPOSITORY }}
        shell: cmd
      - run: echo ${{ vars.GITHUB_SHA }}
        shell: cmd
