name: Details of runner, job, and steps of the job
on:
  workflow_dispatch
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo "${{ toJson(runner) }}"
      - run: echo "${{ toJson(job) }}"
      - run: echo "${{ toJson(steps) }}"
