name: "Github environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ env.github.event.name }}
        shell: cmd
      - run: echo ${{ env.github.repository }}
        shell: cmd
      - run: echo ${{ env.github.sha }}
        shell: cmd
