name: "Github environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ github.event.name }}
        shell: cmd
      - run: echo ${{ github.repository }}
        shell: cmd
      - run: echo ${{ github.sha }}
        shell: cmd
