name: "Parameterized workflow with secrets"
on:
  workflow_dispatch
jobs:
  job:
    environment: Environment1
    env:
      ENVSECRET1: ${{ secrets.ENV_SECRET1 }}
      ENVSECRET2: ${{ secrets.ENV_SECRET2 }}
    runs-on: windows-latest
    steps:
      - run: echo ${{ env.ENVSECRET1 }}
        shell: cmd
      - run: echo ${{ env.ENVSECRET2 }}
        shell: cmd
      - run: echo ${{ secrets.REP_SECRET1 }}
        shell: cmd
      - run: echo ${{ secrets.REP_SECRET2 }}
        shell: cmd
