name: Call to another workflow
on:
  workflow_dispatch:
jobs:
  jobWinShell:
    runs-on: windows-latest
    steps:
      - run: echo "Hello world"
        shell: cmd
  jobPowerShell:
    runs-on: windows-latest
    steps:
      - run: echo "Hello world"
        shell: pwsh
  jobCallToWorkflow:
    runs-on: self-hosted
    steps:
      - uses: ./.github/workflows/task1.yml
