name: "Runner environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ runner.name }}
      - run: echo ${{ runner.os }}
      - run: echo ${{ runner.arch }}
