name: "Parameterized workflow with secrets"
on:
  workflow_dispatch
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo ${{ secrets.ENV_SECRET1 }}
        shell: cmd
      - run: echo ${{ secrets.ENV_SECRET2 }}
        shell: cmd
      - run: echo ${{ secrets.REP_SECRET1 }}
        shell: cmd
      - run: echo ${{ secrets.REP_SECRET2 }}
        shell: cmd
