name: "Github environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo $GITHUB_EVENT_NAME
      - run: echo $GITHUB_REPOSITORY
      - run: echo $GITHUB_SHA
