name: "Runner environment variables"
on:
  workflow_dispatch:
jobs:
  job:
    runs-on: windows-latest
    steps:
      - run: echo $RUNNER_NAME
      - run: echo $RUNNER_OS
      - run: echo $RUNNER_ARCH
